(() => {
  const $=id=>document.getElementById(id);
  const stage=document.querySelector('.stage'),avatar=$('avatar'),statusText=$('statusText'),speechBubble=$('speechBubble'),panel=$('testPanel'),modeToggle=$('modeToggle'),closeTest=$('closeTest'),emotionSelect=$('emotionSelect'),intensityRange=$('intensityRange'),physicsRange=$('physicsRange'),intensityValue=$('intensityValue'),physicsValue=$('physicsValue'),speakingCheck=$('speakingCheck'),rigStatus=$('rigStatus'),speechTestForm=$('speechTestForm'),speechTestInput=$('speechTestInput'),speechTestStop=$('speechTestStop'),rigLayers=[...document.querySelectorAll('[data-layer]')];
  const VALID_EMOTIONS=['neutral','happy','shy','sad','angry','flirty','provocative','focused'],VALID_GESTURES=['nod','tilt','bounce','step'],REQUIRED_LAYERS=['hairBack','body','chest','head','eyesOpen','eyesClosed','mouthClosed','mouthOpen','hairFront'];
  const reducedMotionQuery=matchMedia('(prefers-reduced-motion: reduce)');
  const state={emotion:'neutral',intensity:.55,physics:.62,speaking:false,text:'Ciao. Sono qui.',rig:'pseudo',reducedMotion:reducedMotionQuery.matches,uiMode:'presentation'};
  const motion={targetX:0,targetY:0,x:0,y:0,vx:0,vy:0,rot:0,vrot:0,headX:0,headY:0,headVX:0,headVY:0,headRot:0,headVRot:0,hairX:0,hairY:0,hairVX:0,hairVY:0,hairRot:0,hairVRot:0,chestX:0,chestY:0,chestVX:0,chestVY:0,lookX:0,lookY:0,lastT:performance.now()};
  let blinkTimer=0,blinkUntil=0,mouthTimer=0,lastPointer=null,speechTimer=null;
  const clamp01=(v,f=0)=>{const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(1,n)):f},spring=(p,v,t,k,d,dt)=>{v+=(t-p)*k*dt;v*=Math.exp(-d*dt);p+=v*dt;return[p,v]};
  async function detectRig(){const loaded=new Set();await Promise.all(rigLayers.map(img=>new Promise(resolve=>{const done=ok=>{if(ok)loaded.add(img.dataset.layer);resolve()};if(img.complete)return done(img.naturalWidth>0);img.addEventListener('load',()=>done(true),{once:true});img.addEventListener('error',()=>done(false),{once:true})})));const complete=REQUIRED_LAYERS.every(n=>loaded.has(n));state.rig=complete?'layered':'pseudo';avatar.dataset.rig=state.rig;if(rigStatus)rigStatus.textContent=complete?'Rig layered · blink e lip-sync attivi':'Rig pseudo · bocca reale richiede i layer dedicati';return complete}
  function render(){avatar.className=`avatar state-idle emotion-${state.emotion}`;avatar.dataset.speaking=String(state.speaking);avatar.dataset.rig=state.rig;avatar.dataset.reducedMotion=String(state.reducedMotion);stage.dataset.uiMode=state.uiMode;const root=document.documentElement.style;root.setProperty('--intensity',state.intensity.toFixed(2));root.setProperty('--physics',state.physics.toFixed(2));statusText.textContent=state.speaking?`sta parlando · ${state.emotion}`:`pronta · ${state.emotion}`;speechBubble.textContent=state.text||'';speechBubble.style.visibility=state.text?'visible':'hidden';emotionSelect.value=state.emotion;intensityRange.value=state.intensity;physicsRange.value=state.physics;intensityValue.textContent=`${Math.round(state.intensity*100)}%`;physicsValue.textContent=`${Math.round(state.physics*100)}%`;speakingCheck.checked=state.speaking;panel.hidden=state.uiMode!=='test';modeToggle.setAttribute('aria-pressed',String(state.uiMode==='test'))}
  function setState(n={}){if(n.emotion&&VALID_EMOTIONS.includes(n.emotion))state.emotion=n.emotion;if(n.intensity!==undefined)state.intensity=clamp01(n.intensity,state.intensity);if(n.physics!==undefined)state.physics=clamp01(n.physics,state.physics);if(n.speaking!==undefined)state.speaking=!!n.speaking;if(n.text!==undefined)state.text=String(n.text);if(n.uiMode&&['presentation','test'].includes(n.uiMode))state.uiMode=n.uiMode;render();return{...state}}
  function impulse(x=0,y=0,r=0){if(state.reducedMotion)return;const p=.25+state.physics*1.1;motion.vx+=x*p;motion.vy+=y*p;motion.vrot+=r*p;motion.headVX+=x*p*.16;motion.headVY+=y*p*.11;motion.headVRot+=r*p*.42;motion.hairVX-=x*p*.24;motion.hairVY-=y*p*.16;motion.hairVRot-=r*p*.62;motion.chestVX-=x*p*.08;motion.chestVY-=y*p*.28}
  function gesture(name){if(!VALID_GESTURES.includes(name))return false;avatar.classList.remove(...VALID_GESTURES.map(g=>`gesture-${g}`));void avatar.offsetWidth;avatar.classList.add(`gesture-${name}`);if(name==='nod')impulse(0,9,0);if(name==='tilt')impulse(-5,1,-1.2);if(name==='bounce')impulse(0,-18,.35);if(name==='step')impulse(9,-5,.8);setTimeout(()=>avatar.classList.remove(`gesture-${name}`),950);return true}
  function stopSpeaking(){if(speechTimer!==null)clearTimeout(speechTimer);speechTimer=null;setState({speaking:false})}
  function speak(text,o={}){const s=String(text??'').trim();if(!s)return false;if(speechTimer!==null)clearTimeout(speechTimer);setState({text:s,speaking:true,emotion:o.emotion||state.emotion,intensity:o.intensity??state.intensity});impulse(0,-3,.18);if(o.autoStopMs!==0){const d=o.autoStopMs||Math.max(1300,Math.min(10000,s.length*48));speechTimer=setTimeout(()=>{speechTimer=null;setState({speaking:false})},d)}return true}
  function onMatrixEvent(p){if(!p||typeof p!=='object')return;if(p.type==='luna.state')setState(p);else if(p.type==='luna.speak')speak(p.text||'',p);else if(p.type==='luna.gesture')gesture(p.gesture);else if(p.type==='luna.motion')impulse(p.x||0,p.y||0,p.rotation||0)}
  function updateFace(now){if(state.rig!=='layered'){avatar.dataset.blink='false';avatar.dataset.mouth='closed';return}if(now>blinkTimer){blinkUntil=now+90+Math.random()*70;blinkTimer=now+2200+Math.random()*4200}avatar.dataset.blink=String(now<blinkUntil);if(state.speaking&&now>mouthTimer){avatar.dataset.mouth=avatar.dataset.mouth==='open'?'closed':'open';mouthTimer=now+75+Math.random()*125}else if(!state.speaking)avatar.dataset.mouth='closed'}
  function physicsLoop(now){const dt=Math.min(.032,Math.max(.001,(now-motion.lastT)/1000));motion.lastT=now;if(!state.reducedMotion){const k=28+state.physics*34,d=7.5+(1-state.physics)*3.5;[motion.x,motion.vx]=spring(motion.x,motion.vx,0,k,d,dt);[motion.y,motion.vy]=spring(motion.y,motion.vy,0,k,d,dt);[motion.rot,motion.vrot]=spring(motion.rot,motion.vrot,motion.x*.035,k*.8,d+1.2,dt);[motion.headX,motion.headVX]=spring(motion.headX,motion.headVX,motion.x*.12+motion.lookX*1.4,52,9.4,dt);[motion.headY,motion.headVY]=spring(motion.headY,motion.headVY,motion.y*.08+motion.lookY*.8,50,9.2,dt);[motion.headRot,motion.headVRot]=spring(motion.headRot,motion.headVRot,motion.rot*.28,44,8.8,dt);[motion.hairX,motion.hairVX]=spring(motion.hairX,motion.hairVX,-motion.x*.18,24,5.8,dt);[motion.hairY,motion.hairVY]=spring(motion.hairY,motion.hairVY,-motion.y*.1,22,5.6,dt);[motion.hairRot,motion.hairVRot]=spring(motion.hairRot,motion.hairVRot,-motion.rot*.42,20,5.4,dt);const breath=Math.sin(now/660)*(.18+.22*state.physics);[motion.chestX,motion.chestVX]=spring(motion.chestX,motion.chestVX,-motion.x*.055,31,6.4,dt);[motion.chestY,motion.chestVY]=spring(motion.chestY,motion.chestVY,-motion.y*.16+breath,27,5.8,dt);const root=document.documentElement.style,x=Math.max(-19,Math.min(19,motion.x)),y=Math.max(-19,Math.min(19,motion.y)),r=Math.max(-1.8,Math.min(1.8,motion.rot));root.setProperty('--spring-x',`${x.toFixed(2)}px`);root.setProperty('--spring-y',`${y.toFixed(2)}px`);root.setProperty('--spring-r',`${r.toFixed(3)}deg`);root.setProperty('--head-x',`${motion.headX.toFixed(2)}px`);root.setProperty('--head-y',`${motion.headY.toFixed(2)}px`);root.setProperty('--head-r',`${motion.headRot.toFixed(3)}deg`);root.setProperty('--hair-x',`${motion.hairX.toFixed(2)}px`);root.setProperty('--hair-y',`${motion.hairY.toFixed(2)}px`);root.setProperty('--hair-r',`${motion.hairRot.toFixed(3)}deg`);root.setProperty('--chest-x',`${motion.chestX.toFixed(2)}px`);root.setProperty('--chest-y',`${motion.chestY.toFixed(2)}px`);root.setProperty('--chest-sx',(1+Math.abs(motion.chestX)*.0008).toFixed(4));root.setProperty('--chest-sy',(1+Math.max(-.004,breath*.0024)).toFixed(4))}updateFace(now);requestAnimationFrame(physicsLoop)}
  function onPointerMove(e){const now=performance.now();motion.lookX=(e.clientX/innerWidth-.5)*2;motion.lookY=(e.clientY/innerHeight-.5)*2;document.documentElement.style.setProperty('--look-x',motion.lookX.toFixed(3));document.documentElement.style.setProperty('--look-y',motion.lookY.toFixed(3));if(lastPointer&&!state.reducedMotion){const elapsed=Math.max(8,Math.min(80,now-lastPointer.t)),scale=16.667/elapsed,dx=(e.clientX-lastPointer.x)*scale,dy=(e.clientY-lastPointer.y)*scale;impulse(dx*.035,dy*.02,dx*.002)}lastPointer={x:e.clientX,y:e.clientY,t:now}}
  function setUiMode(mode){setState({uiMode:mode})}
  window.LunaAvatar={version:'0.4.0',setState,getState:()=>({...state}),setUiMode,gesture,impulse,speak,stopSpeaking,onMatrixEvent,emotions:[...VALID_EMOTIONS],gestures:[...VALID_GESTURES],detectRig};
  addEventListener('message',e=>{const d=e.data;if(d&&typeof d==='object'&&String(d.type||'').startsWith('luna.'))onMatrixEvent(d)});addEventListener('pointermove',onPointerMove,{passive:true});addEventListener('pointerdown',()=>impulse(0,-4,0),{passive:true});modeToggle.addEventListener('click',()=>setUiMode(state.uiMode==='test'?'presentation':'test'));closeTest.addEventListener('click',()=>setUiMode('presentation'));emotionSelect.addEventListener('change',e=>setState({emotion:e.target.value}));intensityRange.addEventListener('input',e=>setState({intensity:e.target.value}));physicsRange.addEventListener('input',e=>setState({physics:e.target.value}));speakingCheck.addEventListener('change',e=>e.target.checked?setState({speaking:true}):stopSpeaking());panel.querySelectorAll('[data-gesture]').forEach(b=>b.addEventListener('click',()=>gesture(b.dataset.gesture)));speechTestForm.addEventListener('submit',e=>{e.preventDefault();if(!speak(speechTestInput.value))speechTestInput.focus()});speechTestStop.addEventListener('click',stopSpeaking);if(reducedMotionQuery.addEventListener)reducedMotionQuery.addEventListener('change',e=>{state.reducedMotion=e.matches;render()});else reducedMotionQuery.addListener?.(e=>{state.reducedMotion=e.matches;render()});render();detectRig().then(render);requestAnimationFrame(physicsLoop);
})();
